name = "xynbio-worker"
main = "src/routes.ts"
compatibility_date = "2023-02-16"
node_compat = true

[vars]
JWT_SECRET="ExampleJwtSecret"
FAUNA_SECRET="ExampleFaunaSecret"
GITHUB_TOKEN="YourGitHubToken"
NEXT_WEB_URL="https://www.xyn.bio"
DATA_API_URL="https://data.xyn.bio"
ARCHIVE_REPO="XynBio/XynBio-Archive"